name:
channels:
- conda-forge
dependencies:
- python>=3.11
- pandas>=2.2.2
- numpy>=1.26.4
- matplotlib>=3.8.4
- bokeh>=3.4.1
- anndata>=0.10.7
- scipy>=1.13.1
- requests>=2.32.3
- nest-asyncio>=1.6.0
